### ISSUE TITLE
I encountered a problem running Snapmake ‘snakemake: error: unrecognized arguments: --max-threads’

### ISSUE THREAD

**Issue by JinhuiHe1** [bhattlab/phanta#15]
As described in the title. I am a beginner and may have missed some steps, but I did not find them. I hope the author can help me. Thank you!

**Comment by meenachakra** [comment]
Hi Jinhui, could you please tell us what system you're working with? Computer cluster, local computer, etc? Thank you!

**Comment by JinhuiHe1** [comment]
I work with Computer cluster. Linux version 2.6.32-504.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ).Perhaps due to system reasons, I cannot use the one click installation method either. It will display 'Found conflicts! Looking for incompatible packages.'

**Comment by yipinto** [comment]
--max-threads is an argument of Snakemake. Can you try `snakemake -h` and tell us if you see it listed?
Anyway this argument is not mandatory and you can also use snakemake profile instead.
As for the conflicts in installation did you follow the instructions under troubleshooting? you might want to try installing the few packages listed there instead of the --file /full/path/to/cloned/repo/phanta_env.yaml.

**Comment by JinhuiHe1** [comment]
Thank you for your answers! I have solved my problems.
The reason for the error is that my Snakemake version is too low. I try `conda install -c bioconda snakemake`, but the installed version is 3.3.x. I installed the latest version of snakemaker and resolved it.
Next, I use `conda install -c bioconda bracken=2.7 -c conda-forge` and 'conda install -c bioconda snakemake -c conda-forge' for installation. Successfully resolved 'Found conflicts! Looking for incompatible packages.'
