### ISSUE TITLE
The information of database used

### ISSUE THREAD

**Issue by wen1112** [bhattlab/phanta#18]
I used the phanta on our mock data, but I met a trouble when I try to check the result with our other data. Because some virus which not in Phanta database, were can't sure which one in Phanta database is correspond to our test virus. So could you provide the detail of Phanta database, such as the all virus Phanta contained and the virus information. 
In addition, could you tell me how did your study make non-db correspond with db virus?

**Comment by meenachakra** [comment]
Hi, thank you for your interest in Phanta!

For information about the viruses contained in Phanta's DB, please see the methods section of our [paper](https://www.nature.com/articles/s41587-023-01799-4). Briefly, the viral genomes within the database were sourced from MGV (available at https://portal.nersc.gov/MGV/) and RefSeq viral (downloaded 02/22 using the`kraken2 download-library viral` utility).  

To make non-DB viruses correspond with DB viruses, we calculated ANI between each non-DB virus and the DB viruses. If non-DB virus X had > 95% ANI to a DB virus Y, we said that virus X was the same viral species as Y. We cared about the 95% ANI threshold because we had to calculate true and false positive species for our benchmarking. In our case, you can potentially just see which DB virus has the maximum ANI with your non-DB test virus. 

Do let us know if you would like additional guidance.

**Comment by wen1112** [comment]
Thank you! I want to know if there has a final table of your database? Because the database is MGV+RefSeq, but after download this two databases, you should have done a merge and processing of these two databases? If so, could you provide the final table of Phanta database with all species and they information used? or I could just download this two databases and merge it only to use as reference (If that doesn't make any difference to the final result)？

**Comment by meenachakra** [comment]
Hi!
We included all 189,680 genomes from MGV.
We included all viral genomes specified in the attached file from RefSeq.
[Refseq_viruses_added.txt](https://github.com/bhattlab/phanta/files/11793029/Refseq_viruses_added.txt)

Yes, we had to figure out how to combine their taxonomy - please see the methods section of our paper for how we did that. You can use the taxonomy/names.dmp and taxonomy/nodes.dmp files that are provided with the database to figure out where each genome falls in the taxonomy (e.g., which species it falls under).

Please see [this link](https://bioinformaticsonline.com/blog/view/43916/understanding-dump-files-from-ncbi-taxonomy-database) or other internet resources to understand the format of the names/nodes files.

Please let us know if that doesn't make sense.
