### ISSUE TITLE
The question of Refseq id

### ISSUE THREAD

**Issue by wen1112** [bhattlab/phanta#25]
Hi, I have a question with RefSeq id, for example, the Phanta result provide a id "Faecalibacterium virus Mushu", but the file which you provided last time (Refseq_viruses_added.txt), the species id is "Faecalibacterium phage FP_Mushu", I want to find them the NCBI accession (NC_047913.1), and I met so many times such as this situations. Because the most time I have to search it one by one, instead of use a script to do it directly. So I want to know if there has a table for such a relate infornation?

For example:
Phanta result --> Refseq_viruses_added.txt result
Faecalibacterium virus Mushu --> Faecalibacterium phage FP_Mushu
Klebsiella virus ST147VIM1phi7-1 --> Klebsiella phage ST147-VIM1phi7.1

**Comment by yipinto** [comment]
Hi!
Phanta reports the species level as it appears in ncbi taxonomy. 
For example [this ](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=2734119&lvl=3&lin=f&keep=1&srchmode=1&unlock) is the species level name.
Also see the [subtree](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=2070185) with Faecalibacterium phage FP_Mushu is "no rank" [Mushuvirus mushu](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=2734119&lvl=3&keep=1&srchmode=1&unlock).
Anyhow, since names can change in the taxonomy anyway I recommend using the taxonomic ID to have that information.

**Comment by wen1112** [comment]
Thank you for your responed
