### ISSUE TITLE
Add new vOTUs databases from other sampling compartments

### ISSUE THREAD

**Issue by mhmism** [bhattlab/phanta#34]
Hello, 

I have a shotgun dataset of combined fecal and oral samples. I would like to use phanta, however, it might be only suitable for the fecal samples. I would like to know how to include additional vOTUs to the phanta db to also include phages/viruses coming from other sampling compartments. 

Here is an example of vOTUs databases, I am interested to incorporate:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9160773/
https://pubmed.ncbi.nlm.nih.gov/36399502/

Is there a simple straightforward way for this?

**Comment by CarsonJM** [comment]
Hi @meenachakra I was wondering if you have any update on adding this tutorial? Since the UHGV classify tool has been released (https://github.com/snayfach/UHGV) I am wondering if assigning taxonomy to novel sequences with this tool could aide in adding new viral sequences. I'd be happy to do some testing on my end if that would help!

**Comment by meenachakra** [comment]
Hi Carson, Unfortunately we never got around to doing this! We do hope to complete such a tutorial over the next few months. In the meantime, if you have questions about your specific scenario, please feel free to email us
mchakra@stanford.edu
yishay@stanford.edu

**Comment by meenachakra** [comment]
Hi Carson - we now finally have the tutorial! Thanks for your patience. Please see here -
https://github.com/bhattlab/phanta/blob/main/databases.md

**Comment by CarsonJM** [comment]
@meenachakra Thank you for the update, I am looking forward to customizing the database!
